import type { LucideIcon } from "lucide-react";
import {
  Baby,
  Bell,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Camera,
  FileText,
  GraduationCap,
  HeartHandshake,
  HeartPulse,
  Info,
  Landmark,
  MapPin,
  Newspaper,
  Phone,
  School,
  Shield,
  Siren,
  Stethoscope,
  Target,
  Trees,
  Utensils,
  Waves,
} from "lucide-react";

export const CONTENT_ICONS = {
  briefcase: Briefcase,
  building2: Building2,
  fileText: FileText,
  heartPulse: HeartPulse,
  stethoscope: Stethoscope,
  gradCap: GraduationCap,
  school: School,
  baby: Baby,
  bookOpen: BookOpen,
  siren: Siren,
  phone: Phone,
  shield: Shield,
  landmark: Landmark,
  trees: Trees,
  utensils: Utensils,
  waves: Waves,
  bus: Bus,
  bell: Bell,
  newspaper: Newspaper,
  camera: Camera,
  mapPin: MapPin,
  heartHandshake: HeartHandshake,
  info: Info,
  target: Target,
} as const satisfies Record<string, LucideIcon>;

export type ContentIconKey = keyof typeof CONTENT_ICONS;
