import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Ambulance,
  Banknote,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  CarFront,
  Church,
  Cross,
  Droplets,
  Factory,
  FileText,
  Flame,
  Fuel,
  GraduationCap,
  Hammer,
  HeartPulse,
  Hotel,
  Landmark,
  Laptop,
  Leaf,
  Library,
  MapPin,
  Package,
  PawPrint,
  Phone,
  Pill,
  School,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Sprout,
  Stethoscope,
  Store,
  Tent,
  Toilet,
  TrainFront,
  TreePine,
  Trees,
  Truck,
  UtensilsCrossed,
  Wheat,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";
import type { MapPlaceCategory } from "@/lib/map-place-categories";

const MAP: Partial<Record<MapPlaceCategory, LucideIcon>> = {
  hospital: HeartPulse,
  clinic: Stethoscope,
  pharmacy: Pill,
  diagnostic_center: Activity,
  ambulance: Ambulance,
  blood_bank: Droplets,
  veterinary: PawPrint,
  police: Shield,
  fire_service: Flame,
  disaster_shelter: Tent,
  legal_aid: Hammer,
  union_office: Building2,
  upazila_office: Landmark,
  land_office: FileText,
  passport_office: FileText,
  post_office: Package,
  election_office: Landmark,
  social_service_office: HeartPulse,
  school: School,
  college: GraduationCap,
  university: GraduationCap,
  madrasa: BookOpen,
  coaching_center: Laptop,
  library: Library,
  mosque: Landmark,
  temple: Landmark,
  church: Church,
  pagoda: Landmark,
  restaurant: UtensilsCrossed,
  hotel_food: Hotel,
  fast_food: UtensilsCrossed,
  cafe: UtensilsCrossed,
  bakery: Wheat,
  super_shop: ShoppingCart,
  grocery_store: ShoppingBag,
  bazaar: Store,
  shopping_mall: Building2,
  clothing_store: ShoppingBag,
  electronics_store: Laptop,
  tourist_spot: TreePine,
  park: Trees,
  resort: Hotel,
  guest_house: Hotel,
  historical_place: Landmark,
  bus_stand: Bus,
  train_station: TrainFront,
  ferry_terminal: Truck,
  cng_stand: Fuel,
  car_rental: CarFront,
  bank: Landmark,
  atm: Landmark,
  mobile_banking_agent: Phone,
  microfinance: Banknote,
  electric_office: Zap,
  water_office: Droplets,
  internet_provider: Wifi,
  repair_service: Wrench,
  printing_service: FileText,
  company: Building2,
  factory: Factory,
  job_center: Briefcase,
  training_institute: GraduationCap,
  community_center: Landmark,
  ngo: HeartPulse,
  club: Landmark,
  event_venue: Landmark,
  agriculture_office: Sprout,
  fertilizer_shop: Leaf,
  seed_store: Sprout,
  fishery_office: Droplets,
  livestock_office: PawPrint,
  fuel_station: Fuel,
  public_toilet: Toilet,
  parking: CarFront,
  graveyard: Cross,
  crematorium: Flame,
};

export function mapCategoryIcon(category: MapPlaceCategory): LucideIcon {
  return MAP[category] ?? MapPin;
}
