/**
 * Full Pineapple City / Madhupur map taxonomy (API + UI + contribute).
 * Order: logical groups; keep in sync with `server/src/models/place.model.ts`.
 */
export const MAP_PLACE_CATEGORIES = [
  "hospital",
  "clinic",
  "pharmacy",
  "diagnostic_center",
  "ambulance",
  "blood_bank",
  "veterinary",
  "police",
  "fire_service",
  "disaster_shelter",
  "legal_aid",
  "union_office",
  "upazila_office",
  "land_office",
  "passport_office",
  "post_office",
  "election_office",
  "social_service_office",
  "school",
  "college",
  "university",
  "madrasa",
  "coaching_center",
  "library",
  "mosque",
  "temple",
  "church",
  "pagoda",
  "restaurant",
  "hotel_food",
  "fast_food",
  "cafe",
  "bakery",
  "super_shop",
  "grocery_store",
  "bazaar",
  "shopping_mall",
  "clothing_store",
  "electronics_store",
  "tourist_spot",
  "park",
  "resort",
  "guest_house",
  "historical_place",
  "bus_stand",
  "train_station",
  "ferry_terminal",
  "cng_stand",
  "car_rental",
  "bank",
  "atm",
  "mobile_banking_agent",
  "microfinance",
  "electric_office",
  "water_office",
  "internet_provider",
  "repair_service",
  "printing_service",
  "company",
  "factory",
  "job_center",
  "training_institute",
  "community_center",
  "ngo",
  "club",
  "event_venue",
  "agriculture_office",
  "fertilizer_shop",
  "seed_store",
  "fishery_office",
  "livestock_office",
  "fuel_station",
  "public_toilet",
  "parking",
  "graveyard",
  "crematorium",
] as const;

export type MapPlaceCategory = (typeof MAP_PLACE_CATEGORIES)[number];

export const MAP_CATEGORY_ORDER: MapPlaceCategory[] = [...MAP_PLACE_CATEGORIES];
